config/routes.rb
Rails.application.routes.draw do

  root 'doctors#index'


  resources :doctors, param: :username do
    collection do
      get 'list_female'
      get 'list_male'
    end
  end
  devise_for :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  validates :username, :address, presence: true, uniqueness: {case_sensitive: false}
  validates :gender, presence: true
  scope :list_male, lambda {where(:gender => 'male')}
  scope :list_female, lambda {where(:gender => 'female')}

  def to_param
    username
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  
  def index
    @doctors = Doctor.all
  end

  def show
    @doctor = Doctor.find_by(username: params[:username])
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to doctors_path
    else
      render 'new'
    end
  end

  def edit
    @doctor = Doctor.find_by(username: params[:username])
  end

  def update
    @doctor = Doctor.find_by(username: params[:username])
    if @doctor.update_attributes(doctor_params)
      redirect_to doctor_path(@doctor)
    else
      render 'edit'
    end
  end

  def destroy
    @doctor = Doctor.find_by(username: params[:username])
    @doctor.destroy
    redirect_to doctors_path
  end

  def list_female
    @doctors = Doctor.list_female
  end

  def list_male
    @doctors = Doctor.list_male
  end

  private
    def doctor_params
      params.require(:doctor).permit(:username, :address, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/edit.html.erb
<div class="add doctor">
  <%= link_to("Back", doctors_path, :class => 'action back')%>
  <h1>Update Doctor</h1>
    <%= form_for @doctor do |f| %>
    <table>
      <tr>
        <th>Username</th>
        <td><%= f.text_field :username %>
      </tr>
      <tr>
        <th>Address</th>
        <td><%= f.text_field :address %>
      </tr>
      <tr>
        <th>Gender</th>
        <td><%= f.text_field :gender %>
      </tr>
    </table>
    <%= f.submit "Update user" %></td>
    <% end %>
</div>

app/views/doctors/index.html.erb
<div>

  <% if user_signed_in? %>
  <%= link_to("Add New Doctor", new_doctor_path, :class => 'action new')%><br>
  <%= link_to("Male Doctors", list_male_doctors_path, :class => 'action list_male')%><br>
  <%= link_to("Female Doctors", list_female_doctors_path, :class => 'action list_female')%><br>
  <h1>Doctors' Complete List</h1>
      <table>
        <tr>
          <th>Username</th>
          <th>Address</th>
          <th>Gender</th>
          <th>Action</th>
        </tr>
        <% @doctors.each do |doctor| %>
        <tr>
          <td><%= doctor.username %></td>
          <td><%= doctor.address %></td>
          <td><%= doctor.gender %></td>
          <td class="actions">
          <%= link_to("Show", doctor_path(doctor), :class => 'action show') %>
          <%= link_to("Edit", edit_doctor_path(doctor), :class => 'action edit') %>
          <%= link_to("Delete", doctor_path(doctor), method: :delete) %>
          </td>
        </tr>
        <% end %>
      </table>
  <% else %>
  <h1>List of Doctors</h1>
      <table>
        <tr>
          <th>Current Title</th>
          <th>Username</th>
        </tr>
        <% @doctors.each do |doctor| %>
        <tr>
          <td>Dr.</td>
          <td><%= doctor.username %></td>
        </tr>
        <% end %>
      </table>
  <% end %>


</div>

app/views/doctors/list_female.html.erb
<div>

  <% if user_signed_in? %>
  <%= link_to("Add New Doctor", new_doctor_path, :class => 'action new')%><br>
  <%= link_to("Male Doctors", list_male_doctors_path, :class => 'action list_male')%><br>
  <h1>Female Doctors</h1>
      <table>
        <tr>
          <th>Username</th>
          <th>Address</th>
          <th>Gender</th>
          <th>Action</th>
        </tr>
        <% @doctors.each do |doctor| %>
        <tr>
          <td><%= doctor.username %></td>
          <td><%= doctor.address %></td>
          <td><%= doctor.gender %></td>
          <td class="actions">
          <%= link_to("Show", doctor_path(doctor), :class => 'action show') %>
          <%= link_to("Edit", edit_doctor_path(doctor), :class => 'action edit') %>
          <%= link_to("Delete", doctor_path(doctor), method: :delete) %>
          </td>
        </tr>
        <% end %>
      </table>
  <% end %>


</div>

app/views/doctors/list_male.html.erb
<div>

  <% if user_signed_in? %>
  <%= link_to("Add New Doctor", new_doctor_path, :class => 'action new')%><br>
  <%= link_to("Female Doctors", list_female_doctors_path)%><br>
  <h1>Male Doctors</h1>
      <table>
        <tr>
          <th>Username</th>
          <th>Address</th>
          <th>Gender</th>
          <th>Action</th>
        </tr>
        <% @doctors.each do |doctor| %>
        <tr>
          <td><%= doctor.username %></td>
          <td><%= doctor.address %></td>
          <td><%= doctor.gender %></td>
          <td class="actions">
          <%= link_to("Show", doctor_path(doctor), :class => 'action show') %>
          <%= link_to("Edit", edit_doctor_path(doctor), :class => 'action edit') %>
          <%= link_to("Delete", doctor_path(doctor), method: :delete) %>
          </td>
        </tr>
        <% end %>
      </table>
  <% end %>


</div>

app/views/doctors/new.html.erb
<div class="add doctor">
  <%= link_to("Back", doctors_path, :class => 'action back')%>
  <h1>Add New Doctor</h1>
    <%= form_for @doctor do |f| %>
    <table>
      <tr>
        <th>Username</th>
        <td><%= f.text_field :username %>
      </tr>
      <tr>
        <th>Address</th>
        <td><%= f.text_field :address %>
      </tr>
      <tr>
        <th>Gender</th>
        <td><%= f.text_field :gender %>
      </tr>
    </table>
    <%= f.submit "Create User" %></td>
    <% end %>
</div>

app/views/doctors/show.html.erb
<div>
  <%= link_to("Back", doctors_path, :class => 'action back')%><br>

  <h1>Doctor's Details</h1>
  <table>
    <tr>
      <th>Username</th>
      <th>Address</th>
      <th>Gender</th>
      <th>Action</th>
    </tr>

    <tr>
      <td><%= @doctor.username %></td>
      <td><%= @doctor.address %></td>
      <td><%= @doctor.gender %></td>
      <td class="actions">
      <%= link_to("Edit", '#', :class => 'action edit') %>
      <%= link_to("Delete", '#', :class => 'action delete') %>
      </td>
    </tr>

  </table>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAcMidtermAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <ul class="hmenu">
      <%= render 'devise/menu/registration_items' %>
      <%= render 'devise/menu/login_items'%>
    </ul>
    <%= yield %>
  </body>
</html>